# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_controll_constrs.xdc

# IP: C:/Users/marco/Documents/GitHub/VGA-Controller/generate/memory_obj/memory_obj.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==memory_obj || ORIG_REF_NAME==memory_obj}]

# IP: C:/Users/marco/Documents/GitHub/VGA-Controller/generate/memory_pic/memory_pic.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==memory_pic || ORIG_REF_NAME==memory_pic}]
