# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_pic/memory_pic.xci
# IP: The module: 'memory_pic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_pic/memory_pic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_pic'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_pic/memory_pic.xci
# IP: The module: 'memory_pic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_pic/memory_pic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_pic'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
