# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a50ticsg325-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/managed_ip_project/managed_ip_project.cache/wt [current_project]
set_property parent.project_path C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/managed_ip_project/managed_ip_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_ip -quiet C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj.xci
set_property is_locked true [get_files C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top memory_obj -part xc7a50ticsg325-1L -mode out_of_context

rename_ref -prefix_all memory_obj_

write_checkpoint -force -noxdef memory_obj.dcp

catch { report_utilization -file memory_obj_utilization_synth.rpt -pb memory_obj_utilization_synth.pb }

if { [catch {
  file copy -force C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/managed_ip_project/managed_ip_project.runs/memory_obj_synth_1/memory_obj.dcp C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/ip_user_files/ip/memory_obj]} {
  catch { 
    file copy -force C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj_stub.v C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/ip_user_files/ip/memory_obj
  }
}

if {[file isdir C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/ip_user_files/ip/memory_obj]} {
  catch { 
    file copy -force C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/memory_obj/memory_obj_stub.vhdl C:/Users/marco/Desktop/FH/CHIP2/VGA_Controller/generate/ip_user_files/ip/memory_obj
  }
}
